# Site settings
title: Cycle of blogging and coding
email: kavitha.rising@gmail.com
description: Trying to reignite my passion to write about everything in general and nothing in particular. Ofcourse this is just an excuse to code more.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: streakofjoy
github_username: kavithaRajagopalan

# Build settings
markdown: kramdown
